### PR TITLE
Fix Text fallback theme to match pop os themeing

### PR DESCRIPTION
**Pull request by 13r0ck**
The text fallback theme gets swapped to upon any rendering issues. For example, when (un)plugging a monitor while displaying plymouth, or toggling plymouth during a system upgrade.

This commit replaces the ubuntu-text theme with a pop-text theme, so when users are in this error state their system doesn't look like Ubuntu.

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Comment by n3m0-22** [comment]
There seems to be a problem with this building. I'm not seeing a lot of info other than `dpkg-buildpackage died`.

**Comment by 13r0ck** [comment]
Ill look at that now

**Comment by 13r0ck** [comment]
@n3m0-22 fixed

**Comment by 13r0ck** [comment]
@leviport apparently this is correct. Though plymouth-theme-ubuntu-text doesn't autoremove because it is recommended by `ubuntu-standard` We wont be able to autoremove correctly until our metapackage reorg.

**Review by leviport — APPROVED** [review]
Looking good!
Before:
PXL_20230222_183755029

After:
PXL_20230222_191350793

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
